config/routes.rb
Hackathon228::Application.routes.draw do
  resources :final_grades

  resources :class_ind_grades

  resources :profiles

end

app/models/class_ind_grade.rb
class ClassIndGrade < ActiveRecord::Base
  attr_accessible :course, :grade, :name, :userID, :weight
end

app/models/final_grade.rb
class FinalGrade < ActiveRecord::Base
  attr_accessible :course, :coursename, :grade, :hours, :userID
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :gpa, :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/class_ind_grades_controller.rb
class ClassIndGradesController < ApplicationController
  # GET /class_ind_grades
  # GET /class_ind_grades.json
  def index
    @class_ind_grades = ClassIndGrade.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @class_ind_grades }
    end
  end

  # GET /class_ind_grades/1
  # GET /class_ind_grades/1.json
  def show
    @class_ind_grade = ClassIndGrade.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @class_ind_grade }
    end
  end

  # GET /class_ind_grades/new
  # GET /class_ind_grades/new.json
  def new
    @class_ind_grade = ClassIndGrade.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @class_ind_grade }
    end
  end

  # GET /class_ind_grades/1/edit
  def edit
    @class_ind_grade = ClassIndGrade.find(params[:id])
  end

  # POST /class_ind_grades
  # POST /class_ind_grades.json
  def create
    @class_ind_grade = ClassIndGrade.new(params[:class_ind_grade])

    respond_to do |format|
      if @class_ind_grade.save
        format.html { redirect_to @class_ind_grade, notice: 'Class ind grade was successfully created.' }
        format.json { render json: @class_ind_grade, status: :created, location: @class_ind_grade }
      else
        format.html { render action: "new" }
        format.json { render json: @class_ind_grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /class_ind_grades/1
  # PUT /class_ind_grades/1.json
  def update
    @class_ind_grade = ClassIndGrade.find(params[:id])

    respond_to do |format|
      if @class_ind_grade.update_attributes(params[:class_ind_grade])
        format.html { redirect_to @class_ind_grade, notice: 'Class ind grade was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @class_ind_grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /class_ind_grades/1
  # DELETE /class_ind_grades/1.json
  def destroy
    @class_ind_grade = ClassIndGrade.find(params[:id])
    @class_ind_grade.destroy

    respond_to do |format|
      format.html { redirect_to class_ind_grades_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/final_grades_controller.rb
class FinalGradesController < ApplicationController
  # GET /final_grades
  # GET /final_grades.json
  def index
    @final_grades = FinalGrade.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @final_grades }
    end
  end

  # GET /final_grades/1
  # GET /final_grades/1.json
  def show
    @final_grade = FinalGrade.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @final_grade }
    end
  end

  # GET /final_grades/new
  # GET /final_grades/new.json
  def new
    @final_grade = FinalGrade.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @final_grade }
    end
  end

  # GET /final_grades/1/edit
  def edit
    @final_grade = FinalGrade.find(params[:id])
  end

  # POST /final_grades
  # POST /final_grades.json
  def create
    @final_grade = FinalGrade.new(params[:final_grade])

    respond_to do |format|
      if @final_grade.save
        format.html { redirect_to @final_grade, notice: 'Final grade was successfully created.' }
        format.json { render json: @final_grade, status: :created, location: @final_grade }
      else
        format.html { render action: "new" }
        format.json { render json: @final_grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /final_grades/1
  # PUT /final_grades/1.json
  def update
    @final_grade = FinalGrade.find(params[:id])

    respond_to do |format|
      if @final_grade.update_attributes(params[:final_grade])
        format.html { redirect_to @final_grade, notice: 'Final grade was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @final_grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /final_grades/1
  # DELETE /final_grades/1.json
  def destroy
    @final_grade = FinalGrade.find(params[:id])
    @final_grade.destroy

    respond_to do |format|
      format.html { redirect_to final_grades_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @profiles }
    end
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @profile = Profile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/new
  # GET /profiles/new.json
  def new
    @profile = Profile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/1/edit
  def edit
    @profile = Profile.find(params[:id])
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(params[:profile])

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render json: @profile, status: :created, location: @profile }
      else
        format.html { render action: "new" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /profiles/1
  # PUT /profiles/1.json
  def update
    @profile = Profile.find(params[:id])

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/class_ind_grades_helper.rb
module ClassIndGradesHelper
end

app/helpers/final_grades_helper.rb
module FinalGradesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/class_ind_grades/_form.html.erb
<%= form_for(@class_ind_grade) do |f| %>
  <% if @class_ind_grade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@class_ind_grade.errors.count, "error") %> prohibited this class_ind_grade from being saved:</h2>

      <ul>
      <% @class_ind_grade.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :userID %><br />
    <%= f.number_field :userID %>
  </div>
  <div class="field">
    <%= f.label :course %><br />
    <%= f.number_field :course %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :grade %><br />
    <%= f.number_field :grade %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/class_ind_grades/edit.html.erb
<h1>Editing class_ind_grade</h1>

<%= render 'form' %>

<%= link_to 'Show', @class_ind_grade %> |
<%= link_to 'Back', class_ind_grades_path %>

app/views/class_ind_grades/index.html.erb
<h1>Listing class_ind_grades</h1>

<table>
  <tr>
    <th>Userid</th>
    <th>Course</th>
    <th>Name</th>
    <th>Weight</th>
    <th>Grade</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @class_ind_grades.each do |class_ind_grade| %>
  <tr>
    <td><%= class_ind_grade.userID %></td>
    <td><%= class_ind_grade.course %></td>
    <td><%= class_ind_grade.name %></td>
    <td><%= class_ind_grade.weight %></td>
    <td><%= class_ind_grade.grade %></td>
    <td><%= link_to 'Show', class_ind_grade %></td>
    <td><%= link_to 'Edit', edit_class_ind_grade_path(class_ind_grade) %></td>
    <td><%= link_to 'Destroy', class_ind_grade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Class ind grade', new_class_ind_grade_path %>

app/views/class_ind_grades/new.html.erb
<h1>New class_ind_grade</h1>

<%= render 'form' %>

<%= link_to 'Back', class_ind_grades_path %>

app/views/class_ind_grades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Userid:</b>
  <%= @class_ind_grade.userID %>
</p>

<p>
  <b>Course:</b>
  <%= @class_ind_grade.course %>
</p>

<p>
  <b>Name:</b>
  <%= @class_ind_grade.name %>
</p>

<p>
  <b>Weight:</b>
  <%= @class_ind_grade.weight %>
</p>

<p>
  <b>Grade:</b>
  <%= @class_ind_grade.grade %>
</p>


<%= link_to 'Edit', edit_class_ind_grade_path(@class_ind_grade) %> |
<%= link_to 'Back', class_ind_grades_path %>

app/views/final_grades/_form.html.erb
<%= form_for(@final_grade) do |f| %>
  <% if @final_grade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@final_grade.errors.count, "error") %> prohibited this final_grade from being saved:</h2>

      <ul>
      <% @final_grade.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :userID %><br />
    <%= f.number_field :userID %>
  </div>
  <div class="field">
    <%= f.label :course %><br />
    <%= f.number_field :course %>
  </div>
  <div class="field">
    <%= f.label :coursename %><br />
    <%= f.text_field :coursename %>
  </div>
  <div class="field">
    <%= f.label :grade %><br />
    <%= f.number_field :grade %>
  </div>
  <div class="field">
    <%= f.label :hours %><br />
    <%= f.number_field :hours %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/final_grades/edit.html.erb
<h1>Editing final_grade</h1>

<%= render 'form' %>

<%= link_to 'Show', @final_grade %> |
<%= link_to 'Back', final_grades_path %>

app/views/final_grades/index.html.erb
<h1>Listing final_grades</h1>

<table>
  <tr>
    <th>Userid</th>
    <th>Course</th>
    <th>Coursename</th>
    <th>Grade</th>
    <th>Hours</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @final_grades.each do |final_grade| %>
  <tr>
    <td><%= final_grade.userID %></td>
    <td><%= final_grade.course %></td>
    <td><%= final_grade.coursename %></td>
    <td><%= final_grade.grade %></td>
    <td><%= final_grade.hours %></td>
    <td><%= link_to 'Show', final_grade %></td>
    <td><%= link_to 'Edit', edit_final_grade_path(final_grade) %></td>
    <td><%= link_to 'Destroy', final_grade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Final grade', new_final_grade_path %>

app/views/final_grades/new.html.erb
<h1>New final_grade</h1>

<%= render 'form' %>

<%= link_to 'Back', final_grades_path %>

app/views/final_grades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Userid:</b>
  <%= @final_grade.userID %>
</p>

<p>
  <b>Course:</b>
  <%= @final_grade.course %>
</p>

<p>
  <b>Coursename:</b>
  <%= @final_grade.coursename %>
</p>

<p>
  <b>Grade:</b>
  <%= @final_grade.grade %>
</p>

<p>
  <b>Hours:</b>
  <%= @final_grade.hours %>
</p>


<%= link_to 'Edit', edit_final_grade_path(@final_grade) %> |
<%= link_to 'Back', final_grades_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hackathon228</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.number_field :user %>
  </div>
  <div class="field">
    <%= f.label :gpa %><br />
    <%= f.number_field :gpa %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <tr>
    <th>User</th>
    <th>Gpa</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @profiles.each do |profile| %>
  <tr>
    <td><%= profile.user %></td>
    <td><%= profile.gpa %></td>
    <td><%= link_to 'Show', profile %></td>
    <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
    <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @profile.user %>
</p>

<p>
  <b>Gpa:</b>
  <%= @profile.gpa %>
</p>


<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>